### ISSUE TITLE
Escaped JSON GoogleServiceAccountKey in Options.yml not working 

### ISSUE THREAD

**Issue by murfcam** [looCiprian/GC2-sheet#15]
looCiprian (great work with this) I have an issue in which I CAN get this to function properly when calling the GoogleServiceAccountKey JSON file **separately** in command line but have been **unsuccessful** when placing in options.yml file.  

I have tried escaping manually and using https://www.freeformatter.com/json-escape.html.  I have tried using just the "private_key" portion of key file and even un-escaped json.  I am clearly missing something.  Do you have an example of what the escaped key looks like?  Of course leave out / change the actual key but I have exhausted my ideas to get this to work as one compiled exe.  
<img width="618" alt="option_yaml_escaped_GoogleServiceAccountKey_json" src="https://github.com/user-attachments/assets/367ceab4-af16-4aaf-b7eb-a9875b26c1f6">

**Comment by looCiprian** [comment]
Hi @murfcam, thank you for reaching out and using the project!

To properly use the JSON string you need to remove the new lines as shown below. The other escapes you have are correct.

<img width="642" alt="Screenshot 2024-09-27 at 12 23 59" src="https://github.com/user-attachments/assets/5edb16f0-8628-4152-8faa-176de75b235d">

PS: don't use online services to escape your JSON key since it could be leaked or stolen ;)
